name: website

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - run: pip install cosmo-geff pdoc

      - run: pdoc src/geff -o docs/ -d numpy --no-include-undocumented --footer-text "GEFF v0.1.1" --math --mermaid

      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
